import * as http from 'node:http';
import { ProxyServer } from './proxy/server.js';
import { ProxyConfig } from './types/index.js';
import pc from 'picocolors';

/**
 * Automated end-to-end verification of proxy forwarding, secret sanitization,
 * response caching, and streaming output using an ephemeral mock upstream.
 */
export async function runDemo(): Promise<void> {
  console.log(pc.bold(pc.cyan('\n═══════════════════════════════════════════════════════════════')));
  console.log(pc.bold(pc.cyan('      🛡️  CONTEXT-SHIELD INTERACTIVE DEMO & VERIFICATION       ')));
  console.log(pc.bold(pc.cyan('═══════════════════════════════════════════════════════════════\n')));

  console.log(pc.dim('Starting temporary mock upstream provider...'));

  let capturedPrompt = '';
  const mockUpstream = http.createServer((req, res) => {
    const chunks: Buffer[] = [];
    req.on('data', (c) => chunks.push(Buffer.from(c)));
    req.on('end', () => {
      const body = JSON.parse(Buffer.concat(chunks).toString());
      capturedPrompt = body.messages?.[0]?.content || '';

      if (body.stream) {
        res.writeHead(200, { 'Content-Type': 'text/event-stream' });
        res.write('data: {"choices":[{"delta":{"content":"Analyzing"}}]}\n\n');
        setTimeout(() => {
          res.write('data: {"choices":[{"delta":{"content":" streaming tokens... done!"}}]}\n\n');
          res.write('data: [DONE]\n\n');
          res.end();
        }, 150);
      } else {
        // Simulate network latency (250ms)
        setTimeout(() => {
          res.writeHead(200, { 'Content-Type': 'application/json' });
          res.end(
            JSON.stringify({
              id: 'chatcmpl-demo',
              object: 'chat.completion',
              created: Math.floor(Date.now() / 1000),
              model: body.model,
              choices: [
                {
                  index: 0,
                  message: {
                    role: 'assistant',
                    content: 'Response generated by upstream LLM model.',
                  },
                  finish_reason: 'stop',
                },
              ],
              usage: { prompt_tokens: 45, completion_tokens: 15, total_tokens: 60 },
            })
          );
        }, 250);
      }
    });
  });

  await new Promise<void>((resolve) => mockUpstream.listen(0, '127.0.0.1', () => resolve()));
  const upstreamPort = (mockUpstream.address() as any).port;

  const demoProxyPort = upstreamPort + 10;
  const config: ProxyConfig = {
    port: demoProxyPort,
    host: '127.0.0.1',
    upstreamUrl: `http://127.0.0.1:${upstreamPort}`,
    redactionMode: 'redact',
    enableL1Cache: true,
    l1MaxEntries: 100,
    l1TtlMs: 60000,
    enableL2Cache: true,
    l2DbPath: ':memory:',
    rateLimitPerMinute: 600,
    sessionTokenBudget: 0,
    dailyTokenBudget: 0,
    costPer1kPromptTokens: 0.005,
    costPer1kCompletionTokens: 0.015,
    logLevel: 'info',
    auditLog: true,
  };

  const proxy = new ProxyServer(config);
  await proxy.listen();

  try {
    // Test 1: Secret Redaction & Cache Miss
    console.log(pc.bold(pc.yellow('▶ Step 1: Testing Secret Scanner & Firewall...')));
    const rawPromptWithKey = 'Connect to database using AWS key AKIAIOSFODNN7EXAMPLE and summarize tables';
    console.log(`  Outgoing Prompt: "${pc.red(rawPromptWithKey)}"`);

    const t1Start = Date.now();
    const res1 = await fetch(`http://127.0.0.1:${demoProxyPort}/v1/chat/completions`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model: 'gpt-4o',
        messages: [{ role: 'user', content: rawPromptWithKey }],
      }),
    });
    const t1Duration = Date.now() - t1Start;
    const json1 = (await res1.json()) as any;

    console.log(`  ${pc.green('✓ Secret Intercepted!')} Upstream received sanitized prompt:`);
    console.log(`    "${pc.cyan(capturedPrompt)}"`);
    console.log(`  Proxy Cache Header: ${pc.dim(res1.headers.get('x-contextshield-cache'))}`);
    console.log(`  Roundtrip Latency:  ${pc.yellow(t1Duration + 'ms')} (upstream simulated network trip)`);
    console.log(`  Response:           "${json1.choices[0].message.content}"\n`);

    // Test 2: Cache Hit (Latency & Cost Elimination)
    console.log(pc.bold(pc.yellow('▶ Step 2: Testing L1 Instant Cache Hit (Redundant Query)...')));
    console.log(`  Sending identical prompt again...`);

    const t2Start = Date.now();
    const res2 = await fetch(`http://127.0.0.1:${demoProxyPort}/v1/chat/completions`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model: 'gpt-4o',
        messages: [{ role: 'user', content: rawPromptWithKey }],
      }),
    });
    const t2Duration = Date.now() - t2Start;
    const json2 = (await res2.json()) as any;

    console.log(`  Proxy Cache Header: ${pc.bold(pc.green(res2.headers.get('x-contextshield-cache')))}`);
    console.log(
      `  Cached Latency:     ${pc.bold(pc.green(t2Duration + 'ms'))} (speedup: ${pc.bold((t1Duration / Math.max(1, t2Duration)).toFixed(0) + 'x faster')})`
    );
    console.log(`  Cached Response:    "${json2.choices[0].message.content}"`);
    console.log(`  Tokens Saved:       ${pc.green('60 tokens')} (100% cost avoided on this turn)\n`);

    // Test 3: Streaming SSE Passthrough
    console.log(pc.bold(pc.yellow('▶ Step 3: Testing Zero-Copy Streaming SSE Passthrough...')));
    process.stdout.write('  Stream Output:      ');
    const res3 = await fetch(`http://127.0.0.1:${demoProxyPort}/v1/chat/completions`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model: 'gpt-4o',
        messages: [{ role: 'user', content: 'stream test' }],
        stream: true,
      }),
    });

    const streamText = await res3.text();
    console.log(pc.cyan('Streaming data chunks received successfully:'));
    for (const line of streamText.split('\n')) {
      if (line.trim().startsWith('data:')) {
        console.log(`    ${pc.dim(line.trim())}`);
      }
    }

    // Step 4: Final Telemetry Dashboard
    console.log(pc.bold(pc.yellow('\n▶ Step 4: Real-Time Operational Telemetry:')));
    console.log(proxy.getMetricsCollector().renderDashboard());

    console.log(pc.bold(pc.green('\n✓ Demo completed successfully! All systems fully operational.\n')));
  } finally {
    await proxy.close();
    await new Promise<void>((resolve) => mockUpstream.close(() => resolve()));
  }
}
